# Generated by Django 5.2.6 on 2025-09-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0002_alter_candidatura_bi_alter_candidatura_curso_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidatura',
            name='unique_email_candidatura',
        ),
        migrations.RemoveConstraint(
            model_name='candidatura',
            name='unique_telefone_candidatura',
        ),
        migrations.RemoveConstraint(
            model_name='candidatura',
            name='unique_bi_candidatura',
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='bi',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='candidaturas.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='candidaturas.instituicao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
